name: Chat_Icon_Generator
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/Chat_Icon_Generator
  original_url: https://huggingface.co/spaces/Chris4K/Chat_Icon_Generator

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
